name: Build and deploy ASP.Net Core app to Azure Web App - eShopOnWeb

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build .\src\Web\Web.csproj --configuration Debug

      - name: dotnet publish
        run: dotnet publish .\src\Web\Web.csproj -c Debug -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0192AD0FD5D340C7BAD477AFA2474556 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4E27EFF632D5429BA065B9F744A58799 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BA624EA47A4C4B589FF69F70691BF0C8 }}

      - name: Deploy to Azure Web App - Canada Central
        id: deploy-webapp-canadacentral
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'eShopOnWeb'
          slot-name: 'Production'
          package: .

      - name: Deploy to Azure Web App - East US
        id: deploy-webapp-eastus
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'eShopOnWeb-eastus'
          slot-name: 'Production'
          package: .

      - name: Deploy to Azure Web App - West Europe
        id: deploy-webapp-westeurope
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'eShopOnWeb-westeurope'
          slot-name: 'Production'
          package: .